In [64]:
# we use numpy to wwork with complex mathematical problem data manipulation / processsing and arrays 
import numpy as np # np = nickname/alias
arr1 = np.array([1,2,3])

# 1d arrays
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


In [65]:
print(arr1.mean())

2.0


In [73]:
print(arr1.min())


1


In [74]:
print(arr1.max())

3


In [66]:
#2d arrays
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [67]:
arr1_reshape = np.reshape(arr2, (1,6))
print(arr1_reshape)

[[1 2 3 4 5 6]]


In [3]:
#accessing item in an array
arr1[0] = 50
print(arr1)

[50  2  3]


In [4]:
arr1

array([50,  2,  3])

In [5]:
# list slicing
print(arr1[0:2])

[50  2]


In [6]:
print(arr1)
arr1[1:3] = 33, 44
print(arr1)

[50  2  3]
[50 33 44]


In [7]:
select = [1]
print(arr1[select])

[33]


In [8]:
print(arr1.size)

3


In [9]:
print(arr2.size)

6


In [10]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


In [11]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [12]:
arr3 = np.ones((5,8))
print(arr3)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
arr4 = np.eye(5)
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
arr5 = np.zeros((5,8))
print(arr5)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
arr6 = np.array([[2,3,4,5],[2,3,1,2],[5,4,5,6]], dtype = 'float64')
print(arr6)

[[2. 3. 4. 5.]
 [2. 3. 1. 2.]
 [5. 4. 5. 6.]]


In [16]:
print(arr6.dtype)

float64


In [17]:
print(arr6[0,2])

4.0


In [18]:
print(arr6[0:,:3])

[[2. 3. 4.]
 [2. 3. 1.]
 [5. 4. 5.]]


In [19]:
print(arr5.ndim)

2


In [21]:
type(arr5)

numpy.ndarray

In [22]:
arr5.dtype

dtype('float64')

In [69]:
arr6 = np.array(["a","b","c","d"], dtype = "str")

In [70]:
arr6[0] = "bcd"
print(arr6)

['b' 'b' 'c' 'd']


In [39]:
arr7 = np.array([["Roll No","Name"],["GBAI 1", "ALi"], ["GBAI 2", "Ahmed"] ])
print(arr7)

[['Roll No' 'Name']
 ['GBAI 1' 'ALi']
 ['GBAI 2' 'Ahmed']]


In [54]:
arr7.dtype

dtype('<U7')