In [64]:
# we use numpy to wwork with complex mathematical problem data manipulation / processsing and arrays 
import numpy as np # np = nickname/alias
arr1 = np.array([1,2,3])

# 1d arrays
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


In [65]:
print(arr1.mean())

2.0


In [73]:
print(arr1.min())


1


In [74]:
print(arr1.max())

3


In [66]:
#2d arrays
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [67]:
arr1_reshape = np.reshape(arr2, (1,6))
print(arr1_reshape)

[[1 2 3 4 5 6]]


In [3]:
#accessing item in an array
arr1[0] = 50
print(arr1)

[50  2  3]


In [4]:
arr1

array([50,  2,  3])

In [5]:
# list slicing
print(arr1[0:2])

[50  2]


In [6]:
print(arr1)
arr1[1:3] = 33, 44
print(arr1)

[50  2  3]
[50 33 44]


In [7]:
select = [1]
print(arr1[select])

[33]


In [8]:
print(arr1.size)

3


In [9]:
print(arr2.size)

6


In [10]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


In [11]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [12]:
arr3 = np.ones((5,8))
print(arr3)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
arr4 = np.eye(5)
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
arr5 = np.zeros((5,8))
print(arr5)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
arr6 = np.array([[2,3,4,5],[2,3,1,2],[5,4,5,6]], dtype = 'float64')
print(arr6)

[[2. 3. 4. 5.]
 [2. 3. 1. 2.]
 [5. 4. 5. 6.]]


In [16]:
print(arr6.dtype)

float64


In [17]:
print(arr6[0,2])

4.0


In [18]:
print(arr6[0:,:3])

[[2. 3. 4.]
 [2. 3. 1.]
 [5. 4. 5.]]


In [19]:
print(arr5.ndim)

2


In [21]:
type(arr5)

numpy.ndarray

In [22]:
arr5.dtype

dtype('float64')

In [69]:
arr6 = np.array(["a","b","c","d"], dtype = "str")

In [70]:
arr6[0] = "bcd"
print(arr6)

['b' 'b' 'c' 'd']


In [39]:
arr7 = np.array([["Roll No","Name"],["GBAI 1", "ALi"], ["GBAI 2", "Ahmed"] ])
print(arr7)

[['Roll No' 'Name']
 ['GBAI 1' 'ALi']
 ['GBAI 2' 'Ahmed']]


In [54]:
arr7.dtype

dtype('<U7')

In [1]:
import numpy as np

x_arr = np.array([1,2,3.23], dtype = "int")
print(x_arr)

[1 2 3]


In [2]:
arr6 = np.array([[2,3,4,5],[2,3,1,2],[5,4,5,6]], dtype = 'float64')
print(arr6)
print("\n",arr6[1:3, :4])

[[2. 3. 4. 5.]
 [2. 3. 1. 2.]
 [5. 4. 5. 6.]]

 [[2. 3. 1. 2.]
 [5. 4. 5. 6.]]


In [3]:
arr9 = np.ones((5,8))
print(arr9)

# first two rows 
print("\n\n")
print(arr9[:2 ])

# last 2 elements
print("\n\n")
print(arr9[4:,6:])



[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]



[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]



[[1. 1.]]


In [4]:
arr10 = np.array([[2,3,4,5],[2,3,1,2],[5,4,5,6]], dtype = 'float64')
print(arr6)

[[2. 3. 4. 5.]
 [2. 3. 1. 2.]
 [5. 4. 5. 6.]]


In [5]:
print("max : ",arr10.max())
print("location : ", arr10.argmax())

max :  6.0
location :  11


In [6]:
print("min : ",arr10.min())
print("location : ", arr10.argmin())

min :  1.0
location :  6


In [7]:
arr11 = np.array([1,2,3,4,5])
arr12 = np.array([5,4,3,2,1])
arr13 = np.concatenate((arr11,arr12))
print(arr13)
print(arr11 * arr12)
print(5 * arr13)

[1 2 3 4 5 5 4 3 2 1]
[5 8 9 8 5]
[ 5 10 15 20 25 25 20 15 10  5]


In [8]:
print(np.dot(arr11,arr12))

35


In [9]:
print(np.pi)

3.141592653589793


In [12]:
# arr14 = 5 * arr13
# print(arr14)
print(np.linspace(1,8,200))

[1.         1.03517588 1.07035176 1.10552764 1.14070352 1.1758794
 1.21105528 1.24623116 1.28140704 1.31658291 1.35175879 1.38693467
 1.42211055 1.45728643 1.49246231 1.52763819 1.56281407 1.59798995
 1.63316583 1.66834171 1.70351759 1.73869347 1.77386935 1.80904523
 1.84422111 1.87939698 1.91457286 1.94974874 1.98492462 2.0201005
 2.05527638 2.09045226 2.12562814 2.16080402 2.1959799  2.23115578
 2.26633166 2.30150754 2.33668342 2.3718593  2.40703518 2.44221106
 2.47738693 2.51256281 2.54773869 2.58291457 2.61809045 2.65326633
 2.68844221 2.72361809 2.75879397 2.79396985 2.82914573 2.86432161
 2.89949749 2.93467337 2.96984925 3.00502513 3.04020101 3.07537688
 3.11055276 3.14572864 3.18090452 3.2160804  3.25125628 3.28643216
 3.32160804 3.35678392 3.3919598  3.42713568 3.46231156 3.49748744
 3.53266332 3.5678392  3.60301508 3.63819095 3.67336683 3.70854271
 3.74371859 3.77889447 3.81407035 3.84924623 3.88442211 3.91959799
 3.95477387 3.98994975 4.02512563 4.06030151 4.09547739 4.130653